/*
 * HwBattCtrlConfig.h
 */

#ifndef HWAPIS_HWBATTCTRL_INC_HWBATTCTRLCONFIG_H_
#define HWAPIS_HWBATTCTRL_INC_HWBATTCTRLCONFIG_H_


/* Definition for Batter Status GPIO  */
#define HW_BATTERY_STS_PIN   GPIO_PIN_4
#define HW_BATTERY_STS_PORT  GPIOA

/* Definition for Power Source Indicator GPIO  */

#define HW_PWR_SRC_IND_PIN 		        GPIO_PIN_10
#define HW_PWR_SRC_IND_PORT 			GPIOC

/* Definition for VIN & VIN 12V OUT GPIO Pins */
#define HW_VIN_SENSE_ADC_OUT_PIN 		GPIO_1
#define HW_VIN_SENSE_ADC_12V_OUT_PIN 	GPIO_2
#define HW_VIN_SENSE_ADC_OUT_PORT 		GPIOA
#define HW_VIN_SENSE_ADC_12V_OUT_PORT 	GPIOC

/* Definitions for VIN ADC & VIN 12 ADC */
#define HW_VIN_SENSE_ADC_OUT_CLK_ENABLE()		__HAL_RCC_ADC12_CLK_ENABLE();
#define HW_VIN_SENSE_ADC_OUT_GPIO_CLK_ENABLE()	__HAL_RCC_GPIOA_CLK_ENABLE();

#define HW_VIN_SENSE_ADC_OUT_ADC					    ADC1
#define HW_VIN_SENSE_ADC_OUT_ADC_CHANNEL			    ADC_CHANNEL_1
#define HW_VIN_SENSE_ADC_OUT_ADC_DIVIDER                ADC_CLOCK_ASYNC_DIV64
#define HW_VIN_SENSE_ADC_OUT_RESOLUTION   			    ADC_RESOLUTION_16B
#define HW_VIN_SENSE_ADC_OUT_ADC_ENDIS    			    ADC_SCAN_DISABLE
#define HW_VIN_SENSE_ADC_OUT_CONV         			    ADC_EOC_SINGLE_CONV
#define HW_VIN_SENSE_ADC_OUT_CONTINEOUS_CONV		    ENABLE
#define HW_VIN_SENSE_ADC_OUT_REG_RANK				    ADC_REGULAR_RANK_1
#define HW_VIN_SENSE_ADC_OUT_SAMPLE_TIME			    ADC_SAMPLETIME_1CYCLE_5
#define HW_VIN_SENSE_ADC_OUT_OFFSET					    ADC_OFFSET_NONE

#define HW_VIN_SENSE_ADC_12V_OUT_CLK_ENABLE()		    __HAL_RCC_ADC3_CLK_ENABLE();
#define HW_VIN_SENSE_ADC_12V_OUT_GPIO_CLK_ENABLE()	    __HAL_RCC_GPIOC_CLK_ENABLE();

#define HW_VIN_SENSE_ADC_12V_OUT_ADC					ADC3
#define HW_VIN_SENSE_ADC_12V_OUT_ADC_CHANNEL			ADC_CHANNEL_1
#define HW_VIN_SENSE_ADC_12V_OUT_ADC_DIVIDER            ADC_CLOCK_ASYNC_DIV64
#define HW_VIN_SENSE_ADC_12V_OUT_RESOLUTION				ADC_RESOLUTION_16B
#define HW_VIN_SENSE_ADC_12V_OUT_ADC_ENDIS				ADC_SCAN_DISABLE
#define HW_VIN_SENSE_ADC_12V_OUT_CONV					ADC_EOC_SINGLE_CONV
#define HW_VIN_SENSE_ADC_12V_OUT_CONTINEOUS_CONV		ENABLE
#define HW_VIN_SENSE_ADC_12V_OUT_REG_RANK				ADC_REGULAR_RANK_1
#define HW_VIN_SENSE_ADC_12V_OUT_SAMPLE_TIME			ADC_SAMPLETIME_1CYCLE_5
#define HW_VIN_SENSE_ADC_12V_OUT_OFFSET					ADC_OFFSET_NONE



#endif /* HWAPIS_HWBATTCTRL_INC_HWBATTCTRLCONFIG_H_ */
