/*
 *  HwDoorPOsitionSensorConfig.h
 */

#ifndef TARGETSPECIFIC_HWDOORPOSITIONSENSORCONFIG_H_
#define TARGETSPECIFIC_HWDOORPOSITIONSENSORCONFIG_H_

#include "stm32h7xx_hal.h"

/* Definition for Optical Encoder TIMx clock resources */
#define HW_DOOR_POSITION_SENSOR_ADC_CLK_ENABLE()    __HAL_RCC_ADC3_CLK_ENABLE();
#define HW_DOOR_POSITION_SENSOR_ADC_GPIO_CLK_ENABLE() __HAL_RCC_GPIOC_CLK_ENABLE()

/* Definition for Pressure Sensor 1  */
#define HW_DOOR_POSITION_SENSOR_ADC       				ADC3
#define HW_DOOR_POSITION_SENSOR_ACD_CHANNEL 			ADC_CHANNEL_1
#define HWDOOR_POSITION_SENSOR_ADC_DIVIDER 				ADC_CLOCK_ASYNC_DIV64
#define HWDOOR_POSITION_SENSOR_ADC_RESOLUTION 			ADC_RESOLUTION_8B
#define HWDOOR_POSITION_SENSOR_ADC_ENDIS  				ADC_SCAN_DISABLE
#define HWDOOR_POSITION_SENSOR_ADC_CONV 				ADC_EOC_SINGLE_CONV
#define HWDOOR_POSITION_SENSOR_ADC_CONTINEOUS_CONV 		ENABLE
#define HWDOOR_POSITION_SENSOR_ADC_REG_RANK  			ADC_REGULAR_RANK_1
#define HWDOOR_POSITION_SENSOR_ADC_SAMPLE_TIME 			ADC_SAMPLETIME_1CYCLE_5
#define HWDOOR_POSITION_SENSOR_ADC_OFFSET 				ADC_OFFSET_NONE

#define HW_DOOR_POSITION_SENSOR_ADC_PORT 		GPIOC
#define HW_DOOR_POSITION_SENSOR_ADC_PORT_PIN  	GPIO_PIN_3


#define HW_DOORPOSITION_CLOSED_VALUE     2500
#define HW_DOORPOSITION_OPEN_VALUE       3500
#define HW_DOORPOSITION_HALFOPEN_VALUE   3000




#endif /* TARGETSPECIFIC_HWDOORPOSITIONSENSOR_H_ */
