/*
 *HwBubbleSensorConfig.h
 */

#ifndef HWAPIS_HWBUBBLESENSOR_INC_HWBUBBLESENSORCONFIG_H_
#define HWAPIS_HWBUBBLESENSOR_INC_HWBUBBLESENSORCONFIG_H_


#include "stm32h7xx_hal.h"

/* Definition for Optical Encoder TIMx clock resources */
#define HW_BUBBLE_SENSOR_CLK_ENABLE() __HAL_RCC_GPIOG_CLK_ENABLE()

/* GPIO Definitions */

#define HW_BUBBLE_SENSOR_SIG_PORT 		        GPIOC
#define HW_BUBBLE_SENSOR_SIG_PIN 			    GPIO_PIN_13
#define HW_BUBBLE_SENSOR_SIG_PIN_MODE           GPIO_MODE_IT_RISING
#define HW_BUBBLE_SENSOR_SIG_PIN_PULLUP         GPIO_NOPULL
#define HW_BUBBLE_SENSOR_SIG_PIN_SPEED          GPIO_SPEED_FREQ_LOW


#define HW_BUBBLE_SENSOR_SELFTEST_PORT 			GPIOC
#define HW_BUBBLE_SENSOR_SELFTEST_PIN 			GPIO_PIN_3
#define HW_BUBBLE_SENSOR_SELFTEST_PIN_MODE 		GPIO_MODE_OUTPUT_OD    // Check and change the Mode, if needed
#define HW_BUBBLE_SENSOR_SELFTEST_PIN_PULLUP  	GPIO_NOPULL
#define HW_BUBBLE_SENSOR_SELFTEST_PIN_SPEED     GPIO_SPEED_FREQ_LOW

#endif /* HWAPIS_HWBUBBLESENSOR_INC_HWBUBBLESENSORCONFIG_H_ */
